use serde::{Deserialize, Serialize};

#[derive(Debug, Serialize, Deserialize, Copy, Clone)]
pub enum MapStatus {
    #[serde(rename = "clear")]
    Clear,
    #[serde(rename = "rain")]
    Rain,
    #[serde(rename = "sunny")]
    Sunny,
    #[serde(rename = "sandstorm")]
    Sandstorm,
    Hail,
    Fog,
    Cloudy,
    Snow,
    Blizzard,
    #[serde(rename = "trick_room")]
    TrickRoom,
    Gravity,
    WonderRoom,
    MagicRoom,
    ElectricTerrain,
    GrassyTerrain,
    MistyTerrain,
    Inverse,
    HeavyRain,
    HarshSun,
    Wind,
    MoveBan,
    MysteriousForce,
    SomethingsStirring,
    ItemsSniffed,
    DefaultWeather,
    DefaultMapStatus,
    Status26,
    MercyRevive,
    StairsSensed,
    MapSurveyed,
    MonsterMansion,
    Thief,
    Dark,
    IntrusionCheck,
    MapClearCheck,
    OutlawClearCheck,
    Status36,
    Shopping,
    ShopSecurity,
    Rescued,
    FoeFov,
    Scanner,
    Status42,
    Status43,
    Status44,
    Status45,
    Status46,
    Status47,
    Status48,
    Status49,
}
